brew "git"
brew "neovim"
cask "ghostty" if OS.mac?
brew "container"
brew "ripgrep"

brew "lua-language-server"
brew "bash-language-server"
brew "typescript-language-server"
brew "basedpyright"
brew "gopls"

brew "gh"
brew "opencode"
