brew "mas" if OS.mac?

brew "git"
brew "neovim"
cask "ghostty" unless OS.wsl?
brew "container"
brew "ripgrep"

brew "lua-language-server"
brew "bash-language-server"
brew "typescript-language-server"
brew "basedpyright"
brew "gopls"

brew "gh"
brew "opencode"

cask "obsidian" unless OS.wsl?

